var English_Prep = 
{
    "about": 0,
    "after": 0,
    "ago": 0,
    "around": 0,
    "at": 0,
    "before": 0,
    "by": 0,
    "circa": 0,
    "during": 0,
    "for": 0,
    "from": 0,
    "in": 0,
    "on": 0,
    "past": 0,
    "prior to": 0,
    "since": 0,
    "until": 0,
    "till": 0,
    "up to": 0,
    "up until": 0,
    "aboard": 0,
    "above": 0,
    "across": 0,
    "against": 0,
    "alongside": 0,
    "amid": 0,
    "among": 0,
    "apart from": 0,
    "astride": 0,
    "atop": 0,
    "behind": 0,
    "below": 0,
    "beneath": 0,
    "beside": 0,
    "between": 0,
    "beyond": 0,
    "close to": 0,
    "far": 0,
    "far from": 0,
    "forward of": 0,
    "in between": 0,
    "in front of": 0,
    "inside": 0,
    "into": 0,
    "minus": 0,
    "near": 0,
    "near to": 0,
    "next to": 0,
    "of": 0,
    "off": 0,
    "on board": 0,
    "on top of": 0,
    "onto": 0,
    "upon": 0,
    "opposite": 0,
    "out": 0,
    "out of": 0,
    "outside": 0,
    "outside of": 0,
    "over": 0,
    "round": 0,
    "through": 0,
    "throughout": 0,
    "to": 0,
    "together with": 0,
    "toward/towards": 0,
    "whether": 0,
    "under": 0,
    "underneath": 0,
    "up against": 0,
    "with": 0,
    "within": 0,
    "without": 0,
    "ahead": 0,
    "along": 0,
    "along with": 0,
    "away": 0,
    "away from": 0,
    "by means of": 0,
    "down": 0,
    "further to": 0,
    "off of": 0,
    "toward": 0,
    "towards": 0,
    "up": 0,
    "via": 0,
    "according to": 0,
    "anti": 0,
    "as": 0,
    "as for": 0,
    "as per": 0,
    "as to": 0,
    "as well as": 0,
    "aside from": 0,
    "bar": 0,
    "barring": 0,
    "because of": 0,
    "besides": 0,
    "but for": 0,
    "but": 0,
    "concerning": 0,
    "considering": 0,
    "contrary to": 0,
    "counting": 0,
    "cum": 0,
    "depending on": 0,
    "despite": 0,
    "due to": 0,
    "except": 0,
    "except for": 0,
    "excepting": 0,
    "excluding": 0,
    "given": 0,
    "in addition to": 0,
    "in case of": 0,
    "in face of": 0,
    "in favor of": 0,
    "in favour of": 0,
    "in light of": 0,
    "in spite of": 0,
    "in view of": 0,
    "including": 0,
    "instead of": 0,
    "less": 0,
    "like": 0,
    "notwithstanding": 0,
    "on account of": 0,
    "on behalf of": 0,
    "other than": 0,
    "owing to": 0,
    "pending": 0,
    "per": 0,
    "plus": 0,
    "preparatory to": 0,
    "pro": 0,
    "re": 0,
    "regarding": 0,
    "regardless of": 0,
    "save": 0,
    "save for": 0,
    "saving": 0,
    "than": 0,
    "thanks to": 0,
    "unlike": 0,
    "versus": 0,
    "with reference to": 0,
    "with regard to": 0,
    "worth": 0
}