var KingsList = 
[
    {
        "Names(NIV)": "Saul",
        "Names(CUV)": "扫罗",
        "Nation": "Israel",
        "Span": "42",
        "Date": "",
        "Kinship": "",
        "Spouse(NIV)": "",
        "Prophet": "",
        "Verses": "1Sa9:2",
        "Notes": ""
    },
    {
        "Names(NIV)": "David",
        "Names(CUV)": "大卫",
        "Nation": "Israel",
        "Span": "40",
        "Date": "",
        "Kinship": "son of Jessie",
        "Spouse(NIV)": "",
        "tribe": "",
        "Verses": "1Sa16:19",
        "Notes": ""
    },
    {
        "Names(NIV)": "Solomon",
        "Names(CUV)": "所罗门",
        "Nation": "Israel",
        "Span": "40",
        "Date": "",
        "Kinship": "son of David",
        "Spouse(NIV)": "",
        "Prophet": "",
        "Verses": "\t2Sa5:14",
        "Notes": ""
    },
    {
        "Names(NIV)": "Rehoboam",
        "Names(CUV)": "",
        "Nation": "South",
        "Span": "17",
        "Date": "",
        "Kinship": "",
        "Spouse(NIV)": "",
        "Prophet": "",
        "Verses": "1Ki14:21",
        "Notes": ""
    },
   
    {
        "Names(NIV)": "Abijah",
        "Names(CUV)": "",
        "Nation": "South",
        "Span": "3",
        "Date": "",
        "Kinship": "",
        "Spouse(NIV)": "",
        "Prophet": "",
        "Verses": "1Ki15:1-2",
        "Notes": ""
    },
    {
        "Names(NIV)": "Asa",
        "Names(CUV)": "",
        "Nation": "South",
        "Span": "41",
        "Date": "",
        "Kinship": "",
        "Spouse(NIV)": "",
        "Prophet": "",
        "Verses": "1Ki15:9-10",
        "Notes": ""
    },
    {
        "Names(NIV)": "Jehoshaphat",
        "Names(CUV)": "",
        "Nation": "South",
        "Span": "25",
        "Date": "",
        "Kinship": "",
        "Spouse(NIV)": "",
        "Prophet": "",
        "Verses": "1Ki22:41-42",
        "Notes": ""
    },
    {
        "Names(NIV)": "Jehoram",
        "Names(CUV)": "",
        "Nation": "South",
        "Span": "8",
        "Date": "",
        "Kinship": "",
        "Spouse(NIV)": "",
        "Prophet": "",
        "Verses": "2Ki8:16-17",
        "Notes": ""
    },
    {
        "Names(NIV)": "Ahaziah",
        "Names(CUV)": "",
        "Nation": "South",
        "Span": "1",
        "Date": "",
        "Kinship": "",
        "Spouse(NIV)": "",
        "Prophet": "",
        "Verses": "2Ki8:25-26",
        "Notes": ""
    },
    {
        "Names(NIV)": "Athaliah",
        "Names(CUV)": "",
        "Nation": "South",
        "Span": "6",
        "Date": "",
        "Kinship": "",
        "Spouse(NIV)": "",
        "Prophet": "",
        "Verses": "2Ki11:1-4",
        "Notes": ""
    },
    {
        "Names(NIV)": "Joash",
        "Names(CUV)": "",
        "Nation": "South",
        "Span": "40",
        "Date": "",
        "Kinship": "",
        "Spouse(NIV)": "",
        "Prophet": "",
        "Verses": "2Ki12:1",
        "Notes": ""
    },
    {
        "Names(NIV)": "Amaziah",
        "Names(CUV)": "",
        "Nation": "South",
        "Span": "29",
        "Date": "",
        "Kinship": "",
        "Spouse(NIV)": "",
        "Prophet": "",
        "Verses": "2Ki14:1-2",
        "Notes": ""
    },
    {
        "Names(NIV)": "Azariah (Uzziah)",
        "Names(CUV)": "",
        "Nation": "South",
        "Span": "52",
        "Date": "",
        "Kinship": "",
        "Spouse(NIV)": "",
        "Prophet": "",
        "Verses": "2Ki15:1-2",
        "Notes": ""
    },
    {
        "Names(NIV)": "Totham",
        "Names(CUV)": "",
        "Nation": "South",
        "Span": "16",
        "Date": "",
        "Kinship": "",
        "Spouse(NIV)": "",
        "Prophet": "",
        "Verses": "2Ki15:32-33",
        "Notes": ""
    },
    {
        "Names(NIV)": "Ahaz",
        "Names(CUV)": "",
        "Nation": "South",
        "Span": "16",
        "Date": "",
        "Kinship": "",
        "Spouse(NIV)": "",
        "Prophet": "",
        "Verses": "2Ki16:1-2",
        "Notes": ""
    },
    {
        "Names(NIV)": "Hezekiah",
        "Names(CUV)": "",
        "Nation": "South",
        "Span": "18",
        "Date": "",
        "Kinship": "",
        "Spouse(NIV)": "",
        "Prophet": "",
        "Verses": "2Ki18:1-2",
        "Notes": ""
    },
    {
        "Names(NIV)": "Manasseh",
        "Names(CUV)": "",
        "Nation": "South",
        "Span": "55",
        "Date": "",
        "Kinship": "",
        "Spouse(NIV)": "",
        "Prophet": "",
        "Verses": "2Ki21:1",
        "Notes": ""
    },
    {
        "Names(NIV)": "Amon",
        "Names(CUV)": "",
        "Nation": "South",
        "Span": "2",
        "Date": "",
        "Kinship": "",
        "Spouse(NIV)": "",
        "Prophet": "",
        "Verses": "2Ki21:19",
        "Notes": ""
    },
    {
        "Names(NIV)": "Josiah",
        "Names(CUV)": "",
        "Nation": "South",
        "Span": "31",
        "Date": "",
        "Kinship": "",
        "Spouse(NIV)": "",
        "Prophet": "",
        "Verses": "2Ki22:1",
        "Notes": ""
    },
    {
        "Names(NIV)": "Jehoahaz",
        "Names(CUV)": "",
        "Nation": "South",
        "Span": "3mon",
        "Date": "",
        "Kinship": "",
        "Spouse(NIV)": "",
        "Prophet": "",
        "Verses": "2Ki23:31",
        "Notes": ""
    },
    {
        "Names(NIV)": "Jehoiakim",
        "Names(CUV)": "",
        "Nation": "South",
        "Span": "11",
        "Date": "",
        "Kinship": "",
        "Spouse(NIV)": "",
        "Prophet": "",
        "Verses": "2Ki23:36",
        "Notes": ""
    },
    {
        "Names(NIV)": "Jehoiachin",
        "Names(CUV)": "",
        "Nation": "South",
        "Span": "3mon",
        "Date": "",
        "Kinship": "",
        "Spouse(NIV)": "",
        "Prophet": "",
        "Verses": "2Ki24:8",
        "Notes": ""
    },
    {
        "Names(NIV)": "Zedekiah",
        "Names(CUV)": "",
        "Nation": "South",
        "Span": "11",
        "Date": "",
        "Kinship": "",
        "Spouse(NIV)": "",
        "Prophet": "",
        "Verses": "2Ki24:18",
        "Notes": ""
    },

    {
        "Names(NIV)": "Jeroboam I",
        "Names(CUV)": " ",
        "Nation": "North",
        "Span": "22",
        "Date": "",
        "Kinship": "",
        "Spouse(NIV)": "",
        "Prophet": "",
        "Verses": "1Ki14:20",
        "Notes": ""
    },
    {
        "Names(NIV)": "Nadab",
        "Names(CUV)": "",
        "Nation": "North",
        "Span": "2",
        "Date": "",
        "Kinship": "",
        "Spouse(NIV)": "",
        "Prophet": "",
        "Verses": "1Ki15:25",
        "Notes": ""
    },
    {
        "Names(NIV)": "Baasha",
        "Names(CUV)": "",
        "Nation": "North",
        "Span": "24",
        "Date": "",
        "Kinship": "",
        "Spouse(NIV)": "",
        "Prophet": "",
        "Verses": "1Ki15:33",
        "Notes": ""
    },
    {
        "Names(NIV)": "Elah",
        "Names(CUV)": "",
        "Nation": "North",
        "Span": "2",
        "Date": "",
        "Kinship": "",
        "Spouse(NIV)": "",
        "Prophet": "",
        "Verses": "1Ki16:8",
        "Notes": ""
    },
    {
        "Names(NIV)": "Zimri",
        "Names(CUV)": "",
        "Nation": "North",
        "Span": "7day",
        "Date": "",
        "Kinship": "",
        "Spouse(NIV)": "",
        "Prophet": "",
        "Verses": "1Ki16:15",
        "Notes": ""
    },
    {
        "Names(NIV)": "Tibni",
        "Names(CUV)": "",
        "Nation": "North",
        "Span": "4",
        "Date": "",
        "Kinship": "",
        "Spouse(NIV)": "",
        "Prophet": "",
        "Verses": "1Ki.16:21-22",
        "Notes": ""
    },
    {
        "Names(NIV)": "Omri",
        "Names(CUV)": "",
        "Nation": "North",
        "Span": "12",
        "Date": "",
        "Kinship": "",
        "Spouse(NIV)": "",
        "Prophet": "",
        "Verses": "1Ki16:23",
        "Notes": ""
    },
    {
        "Names(NIV)": "Ahab",
        "Names(CUV)": "",
        "Nation": "North",
        "Span": "22",
        "Date": "",
        "Kinship": "",
        "Spouse(NIV)": "",
        "Prophet": "",
        "Verses": "1Ki16:29",
        "Notes": ""
    },
    {
        "Names(NIV)": "Ahaziah",
        "Names(CUV)": "",
        "Nation": "North",
        "Span": "2",
        "Date": "",
        "Kinship": "",
        "Spouse(NIV)": "",
        "Prophet": "",
        "Verses": "1Ki22:51",
        "Notes": ""
    },
    {
        "Names(NIV)": "Joram",
        "Names(CUV)": "",
        "Nation": "North",
        "Span": "12",
        "Date": "",
        "Kinship": "",
        "Spouse(NIV)": "",
        "Prophet": "",
        "Verses": "2Ki3:1",
        "Notes": ""
    },
    {
        "Names(NIV)": "Jehu",
        "Names(CUV)": "",
        "Nation": "North",
        "Span": "28",
        "Date": "",
        "Kinship": "",
        "Spouse(NIV)": "",
        "Prophet": "",
        "Verses": "2Ki10:36",
        "Notes": ""
    },
    {
        "Names(NIV)": "Jehoahaz",
        "Names(CUV)": "",
        "Nation": "North",
        "Span": "17",
        "Date": "",
        "Kinship": "",
        "Spouse(NIV)": "",
        "Prophet": "",
        "Verses": "2Ki13:1",
        "Notes": ""
    },
    {
        "Names(NIV)": "Jehoash",
        "Names(CUV)": "",
        "Nation": "North",
        "Span": "16",
        "Date": "",
        "Kinship": "",
        "Spouse(NIV)": "",
        "Prophet": "",
        "Verses": "2Ki 13:10",
        "Notes": ""
    },
    {
        "Names(NIV)": "Terohoam IT",
        "Names(CUV)": "",
        "Nation": "North",
        "Span": "41",
        "Date": "",
        "Kinship": "",
        "Spouse(NIV)": "",
        "Prophet": "",
        "Verses": "2Ki14:23",
        "Notes": ""
    },
    {
        "Names(NIV)": "Zechariah",
        "Names(CUV)": "",
        "Nation": "North",
        "Span": "6mon",
        "Date": "",
        "Kinship": "",
        "Spouse(NIV)": "",
        "Prophet": "",
        "Verses": "2Ki15:8",
        "Notes": ""
    },
    {
        "Names(NIV)": "Shallum",
        "Names(CUV)": "",
        "Nation": "North",
        "Span": "1mon",
        "Date": "",
        "Kinship": "",
        "Spouse(NIV)": "",
        "Prophet": "",
        "Verses": "2Ki15:13",
        "Notes": ""
    },
    {
        "Names(NIV)": "Menahem",
        "Names(CUV)": "",
        "Nation": "North",
        "Span": "10",
        "Date": "",
        "Kinship": "",
        "Spouse(NIV)": "",
        "Prophet": "",
        "Verses": "2Ki15:17",
        "Notes": ""
    },
    {
        "Names(NIV)": "Pekahiah",
        "Names(CUV)": "",
        "Nation": "North",
        "Span": "2",
        "Date": "",
        "Kinship": "",
        "Spouse(NIV)": "",
        "Prophet": "",
        "Verses": "2Ki15:23",
        "Notes": ""
    },
    {
        "Names(NIV)": "Pekah",
        "Names(CUV)": "",
        "Nation": "North",
        "Span": "20",
        "Date": "",
        "Kinship": "",
        "Spouse(NIV)": "",
        "Prophet": "",
        "Verses": "2Ki15:27",
        "Notes": ""
    },
    {
        "Names(NIV)": "Hoshea",
        "Names(CUV)": "",
        "Nation": "North",
        "Span": "9",
        "Date": "",
        "Kinship": "",
        "Spouse(NIV)": "",
        "Prophet": "",
        "Verses": "2Ki17:1",
        "Notes": ""
    },
    {
        "Names(NIV)": "",
        "Names(CUV)": "",
        "Nation": "",
        "Span": "",
        "Date": "",
        "Kinship": "",
        "Spouse(NIV)": "",
        "Prophet": "",
        "Verses": "",
        "Notes": ""
    },
    {
        "Names(NIV)": "",
        "Names(CUV)": "",
        "Nation": "",
        "Span": "",
        "Date": "",
        "Kinship": "",
        "Spouse(NIV)": "",
        "Prophet": "",
        "Verses": "",
        "Notes": ""
    },
    {
        "Names(NIV)": "",
        "Names(CUV)": "",
        "Nation": "",
        "Span": "",
        "Date": "",
        "Kinship": "",
        "Spouse(NIV)": "",
        "Prophet": "",
        "Verses": "",
        "Notes": ""
    }
]