var KingsList = 
[
    {
        "Names(NIV)": "Saul",
        "Names(CUV)": "扫罗",
        "Nation": "Israel",
        "Span": "42",
        "Rate": "",
        "Kinship": "",
        "Prophet": "",
        "Verses": "1Sa9:2",
        "RelatedKing": "",
        "Notes": ""
    },
    {
        "Names(NIV)": "David",
        "Names(CUV)": "大卫",
        "Nation": "Israel",
        "Span": "40",
        "Rate": "",
        "Kinship": "son of Jessie",
        "tribe": "",
        "Verses": "1Sa16:19",
        "RelatedKing": "",
        "Notes": ""
    },
    {
        "Names(NIV)": "Solomon",
        "Names(CUV)": "所罗门",
        "Nation": "Israel",
        "Span": "40",
        "Rate": "",
        "Kinship": "son of David",
        "Prophet": "",
        "Verses": "\t2Sa5:14",
        "RelatedKing": "",
        "Notes": ""
    },
    {
        "Names(NIV)": "Jeroboam I",
        "Names(CUV)": "耶罗波安",
        "Nation": "North",
        "Span": "22",
        "Rate": "",
        "Kinship": "",
        "Prophet": "",
        "Verses": "1Ki14:20",
        "RelatedKing": "Rehoboam",
        "Notes": ""
    },
    {
        "Names(NIV)": "Nadab",
        "Names(CUV)": "拿答",
        "Nation": "North",
        "Span": "2",
        "Rate": "",
        "Kinship": "",
        "Prophet": "",
        "Verses": "1Ki15:25",
        "RelatedKing": "Abijah",
        "Notes": ""
    },
    {
        "Names(NIV)": "Baasha",
        "Names(CUV)": "巴沙",
        "Nation": "North",
        "Span": "24",
        "Rate": "",
        "Kinship": "",
        "Prophet": "",
        "Verses": "1Ki15:33",
        "RelatedKing": "Asa",
        "Notes": ""
    },
    {
        "Names(NIV)": "Elah",
        "Names(CUV)": "以拉",
        "Nation": "North",
        "Span": "2",
        "Rate": "",
        "Kinship": "",
        "Prophet": "",
        "Verses": "1Ki16:8",
        "RelatedKing": "Jehoshaphat",
        "Notes": ""
    },
    {
        "Names(NIV)": "Zimri",
        "Names(CUV)": "心利",
        "Nation": "North",
        "Span": "7day",
        "Rate": "",
        "Kinship": "",
        "Prophet": "",
        "Verses": "1Ki16:15",
        "RelatedKing": "Jehoram",
        "Notes": ""
    },
    {
        "Names(NIV)": "Tibni",
        "Names(CUV)": "提比尼",
        "Nation": "North",
        "Span": "4",
        "Rate": "",
        "Kinship": "",
        "Prophet": "",
        "Verses": "1Ki.16:21-22",
        "RelatedKing": "Ahaziah",
        "Notes": ""
    },
    {
        "Names(NIV)": "Omri",
        "Names(CUV)": "暗利",
        "Nation": "North",
        "Span": "12",
        "Rate": "",
        "Kinship": "",
        "Prophet": "",
        "Verses": "1Ki16:23",
        "RelatedKing": "Athaliah",
        "Notes": ""
    },
    {
        "Names(NIV)": "Ahab",
        "Names(CUV)": "亚哈",
        "Nation": "North",
        "Span": "22",
        "Rate": "",
        "Kinship": "wife Jezebel",
        "Prophet": "",
        "Verses": "1Ki16:29",
        "RelatedKing": "Joash",
        "Notes": ""
    },
    {
        "Names(NIV)": "Ahaziah",
        "Names(CUV)": "亚哈谢",
        "Nation": "North",
        "Span": "2",
        "Rate": "",
        "Kinship": "",
        "Prophet": "",
        "Verses": "1Ki22:51",
        "RelatedKing": "Amaziah",
        "Notes": ""
    },
    {
        "Names(NIV)": "Joram",
        "Names(CUV)": "约兰",
        "Nation": "North",
        "Span": "12",
        "Rate": "",
        "Kinship": "",
        "Prophet": "",
        "Verses": "2Ki3:1",
        "RelatedKing": "Azariah (Uzziah)",
        "Notes": ""
    },
    {
        "Names(NIV)": "Jehu",
        "Names(CUV)": "耶户",
        "Nation": "North",
        "Span": "28",
        "Rate": "",
        "Kinship": "",
        "Prophet": "",
        "Verses": "2Ki10:36",
        "RelatedKing": "Totham",
        "Notes": ""
    },
    {
        "Names(NIV)": "Jehoahaz",
        "Names(CUV)": "",
        "Nation": "North",
        "Span": "17",
        "Rate": "",
        "Kinship": "",
        "Prophet": "",
        "Verses": "2Ki13:1",
        "RelatedKing": "Ahaz",
        "Notes": ""
    },
    {
        "Names(NIV)": "Jehoash",
        "Names(CUV)": "",
        "Nation": "North",
        "Span": "16",
        "Rate": "",
        "Kinship": "",
        "Prophet": "",
        "Verses": "2Ki13:10",
        "RelatedKing": "Hezekiah",
        "Notes": ""
    },
    {
        "Names(NIV)": "Jeroboam II",
        "Names(CUV)": "",
        "Nation": "North",
        "Span": "41",
        "Rate": "",
        "Kinship": "",
        "Prophet": "",
        "Verses": "2Ki14:23",
        "RelatedKing": "Manasseh",
        "Notes": ""
    },
    {
        "Names(NIV)": "Zechariah",
        "Names(CUV)": "",
        "Nation": "North",
        "Span": "6mon",
        "Rate": "",
        "Kinship": "",
        "Prophet": "",
        "Verses": "2Ki15:8",
        "RelatedKing": "Amon",
        "Notes": ""
    },
    {
        "Names(NIV)": "Shallum",
        "Names(CUV)": "",
        "Nation": "North",
        "Span": "1mon",
        "Rate": "",
        "Kinship": "",
        "Prophet": "",
        "Verses": "2Ki15:13",
        "RelatedKing": "Josiah",
        "Notes": ""
    },
    {
        "Names(NIV)": "Menahem",
        "Names(CUV)": "",
        "Nation": "North",
        "Span": "10",
        "Rate": "",
        "Kinship": "",
        "Prophet": "",
        "Verses": "2Ki15:17",
        "RelatedKing": "Jehoahaz",
        "Notes": ""
    },
    {
        "Names(NIV)": "Pekahiah",
        "Names(CUV)": "",
        "Nation": "North",
        "Span": "2",
        "Rate": "",
        "Kinship": "",
        "Prophet": "",
        "Verses": "2Ki15:23",
        "RelatedKing": "Jehoiakim",
        "Notes": ""
    },
    {
        "Names(NIV)": "Pekah",
        "Names(CUV)": "",
        "Nation": "North",
        "Span": "20",
        "Rate": "",
        "Kinship": "",
        "Prophet": "",
        "Verses": "2Ki15:27",
        "RelatedKing": "Jehoiachin",
        "Notes": ""
    },
    {
        "Names(NIV)": "Hoshea",
        "Names(CUV)": "",
        "Nation": "North",
        "Span": "9",
        "Rate": "",
        "Kinship": "",
        "Prophet": "",
        "Verses": "2Ki17:1",
        "RelatedKing": "Zedekiah",
        "Notes": ""
    },
    {
        "Names(NIV)": "Rehoboam",
        "Names(CUV)": "罗波安",
        "Nation": "South",
        "Span": "17",
        "Rate": "",
        "Kinship": "",
        "Prophet": "",
        "Verses": "1Ki14:21",
        "RelatedKing": "Jeroboam I",
        "Notes": ""
    },
    {
        "Names(NIV)": "Abijah",
        "Names(CUV)": "亚比亚",
        "Nation": "South",
        "Span": "3",
        "Rate": "",
        "Kinship": "",
        "Prophet": "",
        "Verses": "1Ki15:1-2",
        "RelatedKing": "Nadab",
        "Notes": ""
    },
    {
        "Names(NIV)": "Asa",
        "Names(CUV)": "亚撒",
        "Nation": "South",
        "Span": "41",
        "Rate": "",
        "Kinship": "",
        "Prophet": "",
        "Verses": "1Ki15:9-10",
        "RelatedKing": "Baasha",
        "Notes": ""
    },
    {
        "Names(NIV)": "Jehoshaphat",
        "Names(CUV)": "约沙法",
        "Nation": "South",
        "Span": "25",
        "Rate": "",
        "Kinship": "",
        "Prophet": "",
        "Verses": "1Ki22:41-42",
        "RelatedKing": "Elah",
        "Notes": ""
    },
    {
        "Names(NIV)": "Jehoram",
        "Names(CUV)": "约兰",
        "Nation": "South",
        "Span": "8",
        "Rate": "",
        "Kinship": "",
        "Prophet": "",
        "Verses": "2Ki8:16-17",
        "RelatedKing": "Zimri",
        "Notes": ""
    },
    {
        "Names(NIV)": "Ahaziah",
        "Names(CUV)": "亚哈谢",
        "Nation": "South",
        "Span": "1",
        "Rate": "",
        "Kinship": "",
        "Prophet": "",
        "Verses": "2Ki8:25-26",
        "RelatedKing": "Tibni",
        "Notes": ""
    },
    {
        "Names(NIV)": "Athaliah",
        "Names(CUV)": "亚他利雅(f)",
        "Nation": "South",
        "Span": "6",
        "Rate": "",
        "Kinship": "mother of Ahaziah;daughter of Jezebel",
        "Prophet": "",
        "Verses": "2Ki11:1-4",
        "RelatedKing": "Jehu; Omri",
        "Notes": ""
    },
    {
        "Names(NIV)": "Joash",
        "Names(CUV)": "约阿施",
        "Nation": "South",
        "Span": "40",
        "Rate": "",
        "Kinship": "",
        "Prophet": "",
        "Verses": "2Ki12:1",
        "RelatedKing": "Jehu; Hazael (Syria);",
        "Notes": ""
    },
    {
        "Names(NIV)": "Amaziah",
        "Names(CUV)": "亚玛谢",
        "Nation": "South",
        "Span": "29",
        "Rate": "",
        "Kinship": "",
        "Prophet": "",
        "Verses": "2Ki12:21,14:1-2",
        "RelatedKing": "Ahaziah",
        "Notes": ""
    },
    {
        "Names(NIV)": "Azariah (Uzziah)",
        "Names(CUV)": "",
        "Nation": "South",
        "Span": "52",
        "Rate": "",
        "Kinship": "",
        "Prophet": "",
        "Verses": "2Ki15:1-2",
        "RelatedKing": "Joram",
        "Notes": ""
    },
    {
        "Names(NIV)": "Totham",
        "Names(CUV)": "",
        "Nation": "South",
        "Span": "16",
        "Rate": "",
        "Kinship": "",
        "Prophet": "",
        "Verses": "2Ki15:32-33",
        "RelatedKing": "Jehu",
        "Notes": ""
    },
    {
        "Names(NIV)": "Ahaz",
        "Names(CUV)": "",
        "Nation": "South",
        "Span": "16",
        "Rate": "",
        "Kinship": "",
        "Prophet": "",
        "Verses": "2Ki16:1-2",
        "RelatedKing": "Jehoahaz",
        "Notes": ""
    },
    {
        "Names(NIV)": "Hezekiah",
        "Names(CUV)": "",
        "Nation": "South",
        "Span": "18",
        "Rate": "",
        "Kinship": "",
        "Prophet": "",
        "Verses": "2Ki18:1-2",
        "RelatedKing": "Jehoash",
        "Notes": ""
    },
    {
        "Names(NIV)": "Manasseh",
        "Names(CUV)": "",
        "Nation": "South",
        "Span": "55",
        "Rate": "",
        "Kinship": "",
        "Prophet": "",
        "Verses": "2Ki21:1",
        "RelatedKing": "Jeroboam II",
        "Notes": ""
    },
    {
        "Names(NIV)": "Amon",
        "Names(CUV)": "",
        "Nation": "South",
        "Span": "2",
        "Rate": "",
        "Kinship": "",
        "Prophet": "",
        "Verses": "2Ki21:19",
        "RelatedKing": "Zechariah",
        "Notes": ""
    },
    {
        "Names(NIV)": "Josiah",
        "Names(CUV)": "",
        "Nation": "South",
        "Span": "31",
        "Rate": "",
        "Kinship": "",
        "Prophet": "",
        "Verses": "2Ki22:1",
        "RelatedKing": "Shallum",
        "Notes": ""
    },
    {
        "Names(NIV)": "Jehoahaz",
        "Names(CUV)": "",
        "Nation": "South",
        "Span": "3mon",
        "Rate": "",
        "Kinship": "",
        "Prophet": "",
        "Verses": "2Ki23:31",
        "RelatedKing": "Menahem",
        "Notes": ""
    },
    {
        "Names(NIV)": "Jehoiakim",
        "Names(CUV)": "",
        "Nation": "South",
        "Span": "11",
        "Rate": "",
        "Kinship": "",
        "Prophet": "",
        "Verses": "2Ki23:36",
        "RelatedKing": "Pekahiah",
        "Notes": ""
    },
    {
        "Names(NIV)": "Jehoiachin",
        "Names(CUV)": "",
        "Nation": "South",
        "Span": "3mon",
        "Rate": "",
        "Kinship": "",
        "Prophet": "",
        "Verses": "2Ki24:8",
        "RelatedKing": "Pekah",
        "Notes": ""
    },
    {
        "Names(NIV)": "Zedekiah",
        "Names(CUV)": "",
        "Nation": "South",
        "Span": "11",
        "Rate": "",
        "Kinship": "",
        "Prophet": "",
        "Verses": "2Ki24:18",
        "RelatedKing": "Hoshea",
        "Notes": ""
    }
]