var Special_double = {
    "beg": ["begging", "begged"],
    "blur": ["blurring", "blurred"],
    "flip": ["flipping", "flipped"],
    "plan": ["planning", "planned"],
    "stop": ["stopping", "stopped"],
    "thin": ["thinning", "thinned"],
    "rub": ["rubbing", "rubbed"],
    "split": ["splitting", "(split)"],
    "step": ["stepping", "stepped"],
    "stir": ["stirring", "stirred"],
    "swim": ["swimming", "(swam, swum)"],
    "tap": ["tapping", "tapped"],
    "wrap": ["wrapping", "wrapped"],
    
    // "fix": ["fixing", "fixed"],///
    // "play": ["playing", "played"],
    // "plow": ["plowing", "plowed"],
    //"come": ["coming", "(come, came)"],
    //"date": ["dating", "dated"],
    //"dine": ["dining", "dined"],
    //"hide": ["hiding", "(hid, hidden)"],
    //"hope": ["hoping", "hoped"],
    //"injure": ["injuring", "injured"],
    //"ride": ["riding", "(rode, ridden)"],
    //"slide": ["sliding", "slid"],
    //"smile": ["smiling", "smiled"],
    //"type": ["typing", "typed"],
    //"write": ["writing", "(wrote, written)"],
    // "bleed": ["bleeding", "(bled)"],
    // "eat": ["eating", "(ate; eaten)"],
    // "rain": ["raining", "rained"],
    // "ruin": ["ruining", "ruined"],
    // "seat": ["seating", "seated"],
    // "fool": ["fooling", "fooled"],
    // "dream": ["dreaming", "dreamed/dreamt"],
    // "feel": ["feeling", "felt"],
    // "carry": ["carrying", "carried"],
    // "dry": ["drying", "dried"],
    // "fry": ["frying", "fried"],
    // "fly": ["flying", "(flew flown)"],
    // "reply": ["replying", "replied"],
    // "study": ["studying", "studied"],
    // "try": ["trying", "tried"],
    // "worry": ["worrying", "worried"],
    // "buy": ["buying", "((bought)"],
    // "employ": ["employing", "employed"],
    // "enjoy": ["enjoying", "enjoyed"],
    // "play": ["playing", "played"],
    // "pray": ["praying", "prayed"],
    // "stay": ["staying", "stayed"],
    "acquit": ["acquitting", "acquitted"],
    "admit": ["admitting", "admitted"],
    "begin": ["beginning", "(began, begun)"],
    "commit": ["committing", "committed"],
    "control": ["controlling", "controlled"],
    "deter": ["deterring", "deterred"],
    "excel": ["excelling", "excelled"],
    "occur": ["occurring", "occurred"],
    "prefer": ["preferring", "preferred"],
    "refer": ["referring", "referred"],
    "submit": ["submitting", "submitted"],
    "transfer": ["transferring", "transferred"],
    // "budget": ["budgeting", "budgeted"],
    // "benefit": ["benefiting", "benefited"],
    // "cancel": ["canceling", "canceled"],
    // "counsel": ["counseling", "counseled"],
    // "happen": ["happening", "happened"],
    // "listen": ["listening", "listened"],
    // "marvel": ["marveling", "marveled"],
    // "offer": ["offering", "offered"],
    // "open": ["opening", "opened"],
    // "quarrel": ["quarreling", "quarreled"],
    // "ripen": ["ripening", "ripened"],
    // "visit": ["visiting", "visited"],
    // "travel": ["traveling", "traveled"],
    // "vomit": ["vomiting", "vomited"],
    // "worship": ["worshiping", "worshiped"],
    "quit": ["quitting", "(quit)"],
    //"debut": ["debuting", "debuted"],
    //"exit": ["exiting", "exited"],
    // "tie": ["tying", "tied"],
    // "die": ["dying", "died"],
    // "lie": ["lying", "lied"],
}